-- A script that creates the database hbtn_0d_usa and the table states
-- states have a unique id INT autogenerated and primary key and VARCHAR name
CREATE DATABASE IF NOT EXISTS `hbtn_0d_usa`;
CREATE TABLE IF NOT EXISTS `states` (id INT PRIMARY KEY,
	name VARCHAR(256));
